name: Release

on:
  workflow_call:
    inputs:
      is_prerelease:
        description: Pre-release
        type: boolean
        required: true
      release_tag:
        description: Release tag
        type: string
        required: true
      release_body:
        description: Release description
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
        continue-on-error: true

      - name: Checkout self (for scripts)
        uses: actions/checkout@v4

      - name: Create release directories and zip
        run: |
          chmod +x scripts/prepare-release.sh
          ./scripts/prepare-release.sh

      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: ${{ inputs.release_tag }}
          tag_name: ${{ inputs.release_tag }}
          body: ${{ inputs.release_body }}
          draft: false
          prerelease: ${{ inputs.is_prerelease }}
          make_latest: true
          files: release/*
